
placeholders:
  - "&7Tiempo online: %playtime%"
  - "&7Kills: %kills%"

textures:
  previous_page: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODY0Zjc3OWE4ZTNmZmEyMzExNDNmYTY5Yjk2YjE0ZWUzNWMxNmQ2NjllMTljNzVmZDFhN2RhNGJmMzA2YyJ9fX0="
  next_page: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDllY2NjNWMxYzc5YWE3ODI2YTE1YTdmNWYxMmZiNDAzMjgxNTdjNTI0MjE2NGJhMmFlZjQ3ZTVkZTlhNWNmYyJ9fX0="

messages:
  no_players: "§cNo hay jugadores disponibles."
  selected_player: "§aSeleccionaste a %player%."
  refreshing: "§eRefrescando el menú..."

cache:
  enabled: true
  storage: "yml"
  expiration_time: 3600  # En segundos
