name: MonoxiMenus
version: 0.1
main: monmen.monoxido.MonoxiMenus
api-version: 1.21
depend: [PlaceholderAPI]
author: MonoxiDev
description: Plugin de menú de jugadores con skins en caché.
commands:
  playermenu:
    description: Abre el menú de jugadores.
    usage: /pmenu
    permission: monoximenus.use
  clearskincache:
    description: Borra la caché de skins.
    usage: /clearskincache
    permission: monoximenus.admin
permissions:
  monoximenus.use:
    description: Permite abrir el menú de jugadores.
    default: true
  monoximenus.admin:
    description: Permite borrar la caché de skins.
    default: op
